config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("logs.urls")),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("logs.urls")),
]

logs/urls.py
"""Define padrões de URL para config."""

from django.urls import path

from . import views

app_name = "logs"

urlpatterns = [
    path("", views.index, name="index"),
    path("topics", views.topics, name="topics"),
    path("topics/<int:pk>", views.topic, name="topic"),
    path("new_topic/", views.new_topic, name="new_topic"),
    path("new_entry/<int:pk>", views.new_entry, name="new_entry"),
    path("edit_entry/<int:pk>", views.edit_entry, name="edit_entry"),
]

users/urls.py
"""Define padrões de URL para config."""

from django.urls import path
from django.contrib.auth.views import LoginView


from . import views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
]

logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """Um assunto sobre o qual o usuário está aprendendo."""

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Devolve uma representação em string do modelo."""
        return self.text


class Entry(models.Model):
    """Algo específico aprendido sobre um assunto."""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        """Devolve uma representação em string do modelo."""
        if len(self.text) > 50:
            return self.text[:50] + "..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text"]
        labels = {"text": ""}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]

        labels = {"text": ""}

        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

logs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Entry, Topic
from .forms import EntryForm, TopicForm


def index(request):
    """A página inicial de Learning Log"""
    return render(request, "logs/index.html")


@login_required
def topics(request):
    """Mostra todos os assuntos."""
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    context = {"topics": topics}
    return render(request, "logs/topics.html", context)


@login_required
def topic(request, pk):
    """Mostra um único assunto e todas as suas entradas."""
    topic = get_object_or_404(Topic, id=pk)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "logs/topic.html", context)


@login_required
def new_topic(request):
    """Adiciona um novo assunto."""

    if request.method != "POST":
        # Nenhum dado submetido; cria um formulário em branco

        form = TopicForm()
    else:
        # Dados de POST submetidos; processa os dados

        form = TopicForm(request.POST)

        if form.is_valid():

            new_topic = form.save(commit=False)

            new_topic.owner = request.user

            new_topic.save()

            return HttpResponseRedirect(reverse("logs:topics"))

    context = {"form": form}
    return render(request, "logs/new_topic.html", context)


@login_required
def new_entry(request, pk):
    """Acrescenta uma nova entrada para um assunto em particular."""

    topic = Topic.objects.get(id=pk)

    if request.method != "POST":
        # Nenhum dado submetido; cria um formulário em brancow

        form = EntryForm()
    else:
        # Dados de POST submetidos; processa os dados
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse("logs:topic", args=[pk]))
    context = {"topic": topic, "form": form}
    return render(request, "logs/new_entry.html", context)


@login_required
def edit_entry(request, pk):
    """Edita uma entrada existente."""

    entry = Entry.objects.get(id=pk)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != "POST":
        # Requisição inicial; preenche previamente o formulário

        form = EntryForm(instance=entry)
    else:
        # Dados de POST submetidos; processa os dados

        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():

            form.save()

            return HttpResponseRedirect(reverse("logs:topic", args=[topic.id]))
    context = {"entry": entry, "topic": topic, "form": form}
    return render(request, "logs/edit_entry.html", context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):

    """Faz logout do usuário."""

    logout(request)

    return HttpResponseRedirect(reverse("logs:index"))


def register(request):
    if request.method != "POST":
        # Exibe o formulário de cadastro em branco
        form = UserCreationForm()
    else:
        # Processa o formulário preenchido
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Faz login do usuário e o redireciona para a página inicial
            authenticated_user = authenticate(
                username=new_user.username, password=request.POST["password1"]
            )
            login(request, authenticated_user)

            return HttpResponseRedirect(reverse("logs:index"))

    context = {"form": form}
    return render(request, "users/register.html", context)

logs/templates/logs/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-
scale=1"
    />
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Special+Elite&display=swap");
      * {
        font-family: "Special Elite", cursive;
      }
      body {
        background: #f7971e; /* fallback for old browsers */
        background: -webkit-linear-gradient(
          to right,
          #ffd200,
          #f7971e
        ); /* Chrome 10-25, Safari 5.1-6 */
        background: linear-gradient(
          to right,
          #ffd200,
          #f7971e
        ); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

        height: 100vh;
      }
      footer {
        margin-right: 5px;
      }
      .icon {
        height: 20px;
        padding-bottom: 2px;
      }
    </style>
    <title>Learning Log</title>
    {% bootstrap_css %} {% bootstrap_javascript %}
  </head>
  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button
            type="button"
            class="btn btn-secondary navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#navbar"
            aria-expanded="false"
            aria-controls="navbar"
          >
            <span class="navbar-toggler-icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                stroke-width="2"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M4 8h16M4 16h16"
                />
              </svg>
            </span>
          </button>
          <a class="navbar-brand" href="{% url 'logs:index' %}">Learning Log</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'logs:topics' %}">Topics</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a>Hello, {{ user.username }}.</a></li>
            <li><a href="{% url 'users:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'users:register' %}">Register</a></li>
            <li><a href="{% url 'users:login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <div class="page-header">{% block header %}{% endblock header %}</div>
      <div>{% block content %}{% endblock content %}</div>
    </div>
    <!-- /container -->
    <footer class="d-flex justify-content-end footer fixed-bottom">
      <small class="text-muted">
        Desenvolvido com
        <strong class="text-danger icon">
          <svg
            class="icon"
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5"
            viewBox="0 0 20 20"
            fill="currentColor"
          >
            <path
              fill-rule="evenodd"
              d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
              clip-rule="evenodd"
            />
          </svg>
        </strong>
        por
        <strong>
          <a
            href="https://github.com/alant2031"
            target="_blank"
            class="card-link"
            >Alan Tanaka</a
          >
        </strong>
      </small>
    </footer>
  </body>
</html>

logs/templates/logs/edit_entry.html
{% extends "logs/base.html" %} {% load bootstrap4 %} {% block header %}
<h4><a href="{% url 'logs:topic' topic.id %}">{{ topic }}</a></h4>
{% endblock header %} {% block content %}
<p>Edit entry:</p>
<form action="{% url 'logs:edit_entry' entry.id %}" method="post" class="form">
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <button type="submit" class="btn btn-success">Save changes</button>
  {% endbuttons %}
</form>

{% endblock content %}

logs/templates/logs/index.html
{% extends "logs/base.html" %} {% block header %}

<div class="jumbotron">
  <h1>Track your learning.</h1>
</div>
{% endblock header %} {% block content %}

<h2>
  <a href="{% url 'users:register' %}">Register an account</a> to make your own
  Learning Log, and list the topics you're learning about.
</h2>
<h2>
  Whenever you learn something new about a topic, make an entry summarizing what
  you've learned.
</h2>
{% endblock content %}

logs/templates/logs/new_entry.html
{% extends "logs/base.html" %} {% load bootstrap4 %} {% block header %}
<h4><a href="{% url 'logs:topic' topic.id %}">{{ topic }}</a></h4>
{% endblock header %} {% block content %}
<p>Add a new entry:</p>

<form action="{% url 'logs:new_entry' topic.id %}" method="post" class="form">
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <button type="submit" class="btn btn-primary">Add entry</button>
  {% endbuttons %}
</form>

{% endblock content %}

logs/templates/logs/new_topic.html
{% extends "logs/base.html" %} {% load bootstrap4 %} {% block header %}
<h2>Add a new topic:</h2>
{% endblock header %} {% block content %}

<form action="{% url 'logs:new_topic' %}" method="post" class="form">
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <button name="submit" class="btn btn-primary">Add topic</button>
  {% endbuttons %}
</form>

{% endblock content %}

logs/templates/logs/topic.html
{% extends "logs/base.html" %} {% block header %}
<h2>{{ topic }}</h2>
{% endblock header %} {% block content %}
<p>
  <a href="{% url 'logs:new_entry' topic.id %}">Add new entry</a>
</p>
<ul>
  {% for entry in entries %}
  <div class="card mb-4">
    <div class="card-header">
      <h3>
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small>
          <a href="{% url 'logs:edit_entry' entry.id %}"> Edit entry</a>
        </small>
      </h3>
    </div>
    <div class="card-body">{{ entry.text|linebreaks }}</div>
  </div>
  <!-- card -->
  {% empty %}
  <li>There are no entries for this topic yet.</li>
  {% endfor %}
</ul>

{% endblock content %}

logs/templates/logs/topics.html
{% extends "logs/base.html" %} {% block header %}
<h1>Topics</h1>
{% endblock header %} {% block content %}
<ul>
  {% for topic in topics %}
  <li>
    <h3>
      <a href="{% url 'logs:topic' topic.id %}">{{ topic }}</a>
    </h3>
  </li>
  {% empty %}
  <li>No topics have been added yet.</li>
  {% endfor %}
</ul>
<a href="{% url 'logs:new_topic' %}">Add a new topic</a>
{% endblock content %}

users/templates/users/login.html
{% extends "logs/base.html" %} {% load bootstrap4 %} {% block header %}
<h2>Log in to your account.</h2>
{% endblock header %} {% block content %} {% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
<form method="post" action="{% url 'users:login' %}" class="form">
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <button name="submit" class="btn btn-primary">Login</button>
  {% endbuttons %}
  <input type="hidden" name="next" value="{% url 'logs:index' %}" />
</form>

{% endblock content %}

users/templates/users/register.html
{% extends "logs/base.html" %} {% load bootstrap4 %} {% block header %}
<h2>Create an account.</h2>
{% endblock header %} {% block content %}
<form method="post" action="{% url 'users:register' %}">
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <button name="submit" class="btn btn-primary">Register</button>
  {% endbuttons %}
  <input
    type="hidden"
    name="next"
    value="{% url
'logs:index' %}"
  />
</form>
{% endblock content %}